### ISSUE TITLE
tickets not appearing

### ISSUE THREAD

**Issue by colin-combe** [cmungall/gosf2github#10]
new issues don't appear in my project when I run the gosf2github script.

I run:
./gosf2github.pl -c collab.json -r micommunity/psidev -t MY-TOKEN-HERE psidev-backup-2015-08-20-093343/bugs.json

Output scrolls by, e.g.:

Ticket: ticket_num: 7 of 7 total (last ticket_num=7)
curl -X POST -H "Authorization: token MY-TOKEN-WAS-HERE" -H "Accept: application/vnd.github.golden-comet-preview+json" -d @foo.json https://api.github.com/repos/micommunity/psidev/import/issues
{
  "id": 239059,
  "status": "pending",
  "url": "https://api.github.com/repos/MICommunity/psidev/import/issues/239059",
  "import_issues_url": "https://api.github.com/repos/MICommunity/psidev/import/issues",
  "repository_url": "https://api.github.com/repos/MICommunity/psidev",
  "created_at": "2015-08-20T12:00:10+01:00",
  "updated_at": "2015-08-20T12:00:10+01:00"
}

...but no issues appear in the github project.

**Comment by colin-combe** [comment]
Actually, it seems to work when I provide the -a parameter... perhaps this parameter is not optional after all?

**Comment by cmungall** [comment]
I guess it's optional for me but no one else! 

https://github.com/cmungall/gosf2github/blob/0e981d046d1bed5a3d19cf7d290d7b1aa2661c4c/gosf2github.pl#L12
