### ISSUE TITLE
API returning Not Found

### ISSUE THREAD

**Issue by dseomn** [cmungall/gosf2github#12]
When I try to run the script, I get the error below. Am I running it wrong, or has the API changed?

```
$ ./gosf2github.pl -r dseomn/sf-ticket-test -t [redacted] -u usermap.json -a dseomn -c collab-test.json -s rpstir/tickets tickets.json 
TICKET JSON: tickets.json
Ticket: ticket_num: 1 of 29 total (last ticket_num=29)
curl -X POST -H "Authorization: token [redacted]" -H "Accept: application/vnd.github.golden-comet-preview+json" -d @foo.json https://api.github.com/repos/dseomn/sf-ticket-test/import/issues
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
^C
```

**Comment by cmungall** [comment]
Hmm, I don't think it has, I just ran a test and it still works for me.

Not sure what to suggest, I could take a look at the foo.json file to see if there is anything unusual there. If that doesn't reveal anything, github support are helpful. It's possible you just got unlucky with timing and things may work again.

**Comment by dseomn** [comment]
Thanks, I looked into it a bit more, and I think I found the problem: I needed to generate a new token that has the `public_repo` scope. Could you update the documentation for the `-t` option to say which scopes are needed?

**Comment by cmungall** [comment]
Thanks for this! Reopen if this doesn't solve it for you
