### ISSUE TITLE
'curl' example in README.md is missing a quotation mark.

### ISSUE THREAD

**Issue by luciansmith** [cmungall/gosf2github#13]
README.md contains the following example curl line:

curl -H "Authorization: token TOKEN  https://api.github.com/repos/obophenotype/cell-ontology/collaborators > cell-collab.json

However, it needs a quotation mark after TOKEN:

curl -H "Authorization: token TOKEN"  https://api.github.com/repos/obophenotype/cell-ontology/collaborators > cell-collab.json

(It might also be nice to emphasize that 'token' is a keyword, and 'TOKEN' is a stand-in for the actual token.)

**Comment by rusefi** [comment]
+1
Would a pull request help to address this little issue?

**Comment by cmungall** [comment]
Thanks! Sorry about the delay. Yes in general PRs welcome!
