### ISSUE TITLE
Tickets from json file get loaded out of order

### ISSUE THREAD

**Issue by elserj** [cmungall/gosf2github#9]
Not sure why, or if it matters, but I get the following when trying to do a dry-run for the PO issue tracker.  Note that ticket numbers seem to be jumping around rather then be sequential as expected.  Exported json file sent via PM. for testing.

TICKET JSON: plant-ontology-po-term-requests.json  
Ticket: 1 of 601  
curl -X POST -H "Authorization: token TOKEN_ID" -H "Accept: application/vnd.github.golden-comet-preview+json" -d @foo.json https://api.github.com/repos/Planteome/plant-ontology/import/issues  
DRY RUN: not executing  
Ticket: 28 of 601  
curl -X POST -H "Authorization: token TOKEN_ID" -H "Accept: application/vnd.github.golden-comet-preview+json" -d @foo.json https://api.github.com/repos/Planteome/plant-ontology/import/issues  
DRY RUN: not executing  
Ticket: 2 of 601  
curl -X POST -H "Authorization: token TOKEN_IDa" -H "Accept: application/vnd.github.golden-comet-preview+json" -d @foo.json https://api.github.com/repos/Planteome/plant-ontology/import/issues
DRY RUN: not executing
Ticket: 574 of 601
curl -X POST -H "Authorization: token TOKEN_ID" -H "Accept: application/vnd.github.golden-comet-preview+json" -d @foo.json https://api.github.com/repos/Planteome/plant-ontology/import/issues
DRY RUN: not executing
Ticket: 3 of 601
curl -X POST -H "Authorization: token TOKEN_ID" -H "Accept: application/vnd.github.golden-comet-preview+json" -d @foo.json https://api.github.com/repos/Planteome/plant-ontology/import/issues
DRY RUN: not executing

**Comment by cmungall** [comment]
Confirmed with @elserj - until now the json dump from sf was always pre-sorted but we seem to have hit at least 1 exception
